config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web, at: '/sidekiq'

  root   'home#index'
  get    '/help',    to: 'home#help'
  get    '/about',   to: 'home#about'
  get    '/contact', to: 'home#contact'
  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :account_activations, only: [:edit],  param: :token, :constraints => {:token => /[^\/]+/}
  get '/webhooks',  to: 'mailgun_webhooks#csv', as: :mailgun_webhooks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token, :activation_token

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                                    format: { with: VALID_EMAIL_REGEX },
                                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }

  before_save :downcase_email
  before_create :create_activation_digest

  has_secure_password

  class << self

    # Returns the hash digest of the given string.
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    # Returns a random token.
    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  def send_activation_email
    SendActivationMailWorker.perform_async(self.id, self.activation_token)
  end

  def activate
    update_attribute(:activated, true)
    update_attribute(:activated_at, Time.zone.now)
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  private

  def downcase_email
    self.email = email.downcase
  end

  def create_activation_digest
    self.activation_token  = User.new_token
    self.activation_digest = User.digest(activation_token)
  end
end

app/controllers/account_activations_controller.rb
class AccountActivationsController < ApplicationController
  def edit
    user = User.find_by(email: params[:email])

    if user && !user.activated? && user.authenticated?(:activation, params[:token])
      user.activate
      log_in user
      flash[:success] = "Account activated!"
    else
      flash[:danger] = "Invalid activation link"
    end

    redirect_to root_url
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/mailgun_webhooks_controller.rb
class MailgunWebhooksController < ApplicationController
  def csv
    settings = Rails.application.config.action_mailer.mailgun_settings
    data = MailgunSupress.new(settings[:api_key], settings[:domain])
    flash[:info] = "Faced some problem in setting tracking the events"
    redirect_to root_url
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      if user.activated?
        log_in user
        params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      else
        message  = "Account not activated. "
        message += "Check your email for the activation link."
        flash[:warning] = message
      end
      redirect_to root_url
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:info] = "Please check your email to activate your account."

      redirect_to root_url
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end
end

app/helpers/account_activations_helper.rb
module AccountActivationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  include SessionsHelper

  #check if a css file exists or not before loading the same
  def stylesheet_exists?(stylesheet)
    stylesheet = "#{Rails.root}/app/assets/stylesheets/#{stylesheet}.css"
    File.exists?(stylesheet) || File.exists?("#{stylesheet}.sass")
  end

  #check if a js file exists or not before loading the same
  def javascript_exists?(script)
    script = "#{Rails.root}/app/assets/javascripts/#{script}.js"
    extensions = %w(.coffee .erb .coffee.erb) + [""]
    extensions.inject(false) do |truth, extension|
      truth || File.exists?("#{script}#{extension}")
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mailgun_webhooks_helper.rb
module MailgunWebhooksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(:remember, cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  private

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  The <a href="https://documentation.mailgun.com"><em>about</em></a>
</p>

app/views/home/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>
  The <a href="https://documentation.mailgun.com"><em>contact</em></a>
</p>

app/views/home/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="https://documentation.mailgun.com">help</a>.
</p>

app/views/home/index.html.erb
<% provide(:title, "Home") %>
<% if logged_in? %>
  <% if current_user.activated? %>
<p>You are our premium user</p>
<% else %>
<p>Please activated you account</p>
  <% end %>
<% else %>
  <%= link_to 'Sign up', signup_path, class: 'btn btn-primary' %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="adjust-nav">
    <div class="navbar-header">
      <a class="navbar-brand" href=<%= root_url %>><i class="wi wi-night-sleet"></i>&nbsp;MailGun</a>
      <nav class="pull-right">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", root_url %></li>
          <li><%= link_to "Help", help_path %></li>
          <% if logged_in? %>
            <% if current_user.admin %>
              <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">WebHooks
                  <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to 'Click', mailgun_webhooks_path(type: 'click') %></li>
                  <li><%= link_to 'Bounce', mailgun_webhooks_path(type: 'bounce') %></li>
                </ul>
              </li>
              <% end %>
            <li><%= link_to "Log out", logout_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Signup", signup_path %></li>
            <li><%= link_to "Log in", login_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</div>

app/views/layouts/_side_menu.html.erb
<nav class="navbar-default navbar-side" role="navigation">
  <div class="sidebar-collapse">
    <ul class="nav" id="main-menu">
      <li>
        <%= link_to root_path do %>
          <i class="fa fa-desktop "></i>Dashboard
        <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title><%= yield :title %> | Mailgun</title>
    <%= stylesheet_link_tag    'application', media: 'all'%>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />
    <%= stylesheet_link_tag params[:controller] if stylesheet_exists?(params[:controller]) %>
    <%= javascript_include_tag params[:controller] if javascript_exists?(params[:controller]) %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div id="wrapper">
      <%= render partial: 'layouts/header' %>
      <%= render partial: 'layouts/side_menu' %>
      <div id="page-wrapper">
        <div id="page-inner">
          <div class="row">
            <%= render partial: 'shared/flash_messages' %>
            <%= yield %>
          </div>
        </div>
      </div>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'shared/error_messages' %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>